server:
  port: 8090

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://%{DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgress}
    jpa:
        hibernate:
            ddl-auto: create-drop
#          //DATA DEFINITION LANGUAGE. NONE: Sempre que inicializa ele apaga e cria a tabela
        show-sql: true
        properties:
            hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true